knp_paginator:
  page_range: 5
  default_options:
    default_limit: 10
  template:
    pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
    sortable: '@KnpPaginator/Pagination/bootstrap_v5_fa_sortable_link.html.twig'